lim:
  tcpPort: 9000
  webSocketPort: 19000
  bossThreadSize: 1
  workThreadSize: 8
  heartBeatTime: 3000 #心跳超时时间 单位毫秒
  # 多端同步模式：1 只允许一端在线，手机/电脑/web 踢掉除了本client+imei的设备
  #            2 允许手机/电脑的一台设备 + web在线 踢掉除了本client+imei的非web端设备
  #            3 允许手机和电脑单设备 + web 同时在线 踢掉非本client+imei的同端设备
  #            4 允许所有端多设备登录 不踢任何设备
  loginModel: 1

  redis:
    model: cluster # 单机模式：single 哨兵模式：sentinel 集群模式：cluster
    database: 1
    password: shiju1283
    timeout: 4000 # 超时时间
    poolMinIdle: 8 #最小空闲数
    poolConnTimeout: 3000 # 连接超时时间(毫秒)
    poolSize: 10 # 连接池大小
    single:
      address: 106.52.219.98:7361
    sentinel:
      nodes: 106.52.219.98:7361,106.52.219.98:7362,106.52.219.98:7363,106.52.219.98:7364,106.52.219.98:7365,106.52.219.98:7366
      master: redis-master
    cluster: #redis单机配置
      nodes: 106.52.219.98:7361,106.52.219.98:7362,106.52.219.98:7363,106.52.219.98:7364,106.52.219.98:7365,106.52.219.98:7366

  rabbitmq:
    host: 106.52.219.98
    port: 5672
    virtualHost: /
    userName: shiju1283
    password: shiju1283

  zkConfig:
    zkAddr: 106.52.219.98:2181,106.52.219.98:2182,106.52.219.98:2183
    zkConnectTimeOut: 10000