spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://106.52.219.98:3306/im?serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false&characterEncoding=UTF8
    username: root
    password: shiju1283
  mvc:
    path match:
      matching-strategy: ANT_PATH_MATCHER
  application:
    name: im-core
  main:
    allow-circular-references: true

# logger配置
logging:
  config: classpath:logback-spring.xml

server:
  port: 8000
  servlet:
    context-path: /im

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:mapper/*.xml
  global-config:
    db-config:
      update-strategy: not_empty

#应用配置
appConfig:
  zkAddr: 106.52.219.98:2181,106.52.219.98:2182,106.52.219.98:2183 # zk连接地址
  zkConnectTimeOut: 10000 # zk超时时间
  imRouteWay: 3 # 路由策略 1随机 2轮循 3一致性hash
  consistentHashWay: 1 # 如果选用一致性hash的话具体hash算法 1 TreeMap 2 自定义Map
